server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///C:\Users\WINDOWS\IdeaProjects\git-native-repo
        git:
#          uri: file://C:\Users\WINDOWS\IdeaProjects\git-local-config
          uri: https://github.com/JunHyungJang/msa_server_config_repo
#
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest


management:
  endpoints:
    web:
      exposure:
        include: health,busrefresh